config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'information#index'
  get 'information/auto_complete' => 'information#auto_complete'
  get 'information/search' => 'information#search'
  post 'information/update_sort' => 'information#update_sort'
  post 'information/new' => 'information#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/info.rb
class Info < ApplicationRecord
  acts_as_list
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/information_controller.rb
class InformationController < ApplicationController

  before_action :set_infos, only: [:index, :update_sort]

  def index
  end

  def new
    Info.create(name: "#{params["name"].capitalize}")
    @infos = Info.order("position")
  end

  def auto_complete
    @results = Info.where("name LIKE ?", "%#{params['track'].capitalize}%").pluck(:name)
    @results = @results.present? ? @results : nil
    render json: @results
  end

  def search
    @result = Info.find_by("name = ?", "#{params['track']}")
  end

  def update_sort
    new_sequence = params["infos"]
    new_sequence.each_with_index do |person, index|
      position = index+1
      Info.find(person).update(position: position)
    end
    head 200, content_type: "text/html"
 end

  private

  def set_infos
    @infos = Info.order("position")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_list.html.erb
<% infos.each do |info| %>   
  <%= content_tag(:li, id: "#{info.id}") do %>
    <%= info.name %> 
  <% end %>
<% end %> 

app/views/information/_search.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>Available Results</h4><hr>
        <dl>  
          <dt>Title</dt>
          <dd><%= result&.name %></dd>
        </dl>
      <hr>
    </div>
  </div>
</div>

app/views/information/index.html.erb
<br><br>
<% if flash[:alert] %>
  <div class="alert alert-warning"><%= flash[:alert] %></div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <h3>For Drag and Drop</h3><hr>   
      <ul id="names_for_drag_and_drop">
        <%= render partial: "information/list", locals: { infos: @infos } %>
      </ul>
    </div>

    <div class="col-sm" style="width: 400px">
      <h3>Search with autocomplete</h3><hr>
      <%= form_tag( information_search_path, remote: true, method: :get, class: "search_form") do %>
        <div class="form-group">
          <%= text_field_tag :track, nil, placeholder: 'eg. Aaa', class: 'form-control', id: 'form_field' %>
        </div>
        <%= button_tag 'Search', data: { disable_with: "Searching..."}, class: 'btn btn-success btn-block' %>
      <% end %>
    </div>

    <div class="col-sm" style="width: 400px">

      <h3>Add new name</h3><hr>
      <%= form_tag( information_new_path, remote: true, method: :post, class: "new_form") do %>
        <div class="form-group">
          <%= text_field_tag :name, nil, placeholder: 'eg. Aaa', class: 'form-control', id: "new_form_field" %>
        </div>
        <%= button_tag 'Submit', data: { disable_with: "Adding..."}, class: 'new_form btn btn-warning btn-block' %>
      <% end %>
      <br></br>

      <h3>Search</h3>
      <div class="select2_div">
        <%= select_tag "Name", options_from_collection_for_select(Info.all, :id, :name), class: 'js-searchable', include_blank: true  %>
      </div>
    </div>

  </div>
</div>

<hr>
<div class="results" ></div>

app/views/information/new.js.erb
document.getElementById("names_for_drag_and_drop").innerHTML = "<%= j render partial: 'information/list', locals: { infos: @infos } %>";
$(".new_form").trigger('reset');

app/views/information/search.js.erb
$(".results").html("<%= j render partial: '/information/search', locals: { result: @result } %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoComplete</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>